version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11  # Using a pre-built CircleCI image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Download NLTK data
          command: |
            . venv/bin/activate
            python nltkdownload.py
      - run:
          name: Lint with flake8
          command: |
            . venv/bin/activate
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - run:
          name: Test with pytest
          command: |
            . venv/bin/activate
            pytest

workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test 