apiVersion: v1
kind: Service
metadata:
  name: biztel-api-service
spec:
  selector:
    app: biztel-api
  ports:
    - protocol: TCP
      port: 80  # Expose the service on port 80
      targetPort: 8000  # Forward traffic to the container's port 8000
  type: LoadBalancer  # Use a LoadBalancer to expose the service outside the cluster 